name: 'Terraform'

on:
  push:
    branches: [ "main" ]

jobs: 
  terraform:
    runs-on: ubuntu-latest 
    name: 'terraform'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-secret-access-key: ${{ secrets.AWS_SECRETS_ACCESS_KEY }}
          #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: eu-north-1
      - name: terraform init 
        run: terraform init 

